<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>frostillicus_framework</groupId>
	<artifactId>frostillicus.framework</artifactId>
	<version>1.4.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>frostillic.us Framework</name>
	<url>https://github.com/jesse-gallagher/XPages-Scaffolding</url>

	<modules>
		<module>bundles/frostillicus.framework.plugin</module>
		<module>tests/frostillicus.framework.plugin.test</module>
		<module>features/frostillicus.framework.feature</module>
		<module>releng/frostillicus.framework.update</module>
		<module>releng/framework-dist</module>
	</modules>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.compiler.release>8</maven.compiler.release>
		<tycho-version>4.0.13</tycho-version>
	</properties>

	<scm>
		<url>https://github.com/jesse-gallagher/XPages-Scaffolding</url>
		<connection>scm:git:https://github.com/jesse-gallagher/XPages-Scaffolding.git</connection>
	</scm>
	<issueManagement>
		<url>https://github.com/jesse-gallagher/XPages-Scaffolding/issues</url>
	</issueManagement>
	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
			<comments>A business-friendly OSS license</comments>
		</license>
	</licenses>

	<repositories>
		<repository>
			<id>Eclipse</id>
			<layout>p2</layout>
			<url>https://download.eclipse.org/releases/neon/</url>
		</repository>
		<repository>
			<id>notes</id>
			<layout>p2</layout>
			<url>${notes-platform}</url>
		</repository>
		<repository>
			<id>openntf</id>
			<url>https://artifactory.openntf.org/openntf</url>
		</repository>
	</repositories>
	
	<dependencies>
		<dependency>
			<groupId>org.openntf.domino</groupId>
			<artifactId>org.openntf.domino</artifactId>
			<version>12.0.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openntf.domino</groupId>
			<artifactId>org.openntf.formula</artifactId>
			<version>12.0.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openntf.domino</groupId>
			<artifactId>javolution</artifactId>
			<version>6.1.0-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openntf.domino</groupId>
			<artifactId>org.openntf.domino.java.api.corba.patch</artifactId>
			<version>1.0.0</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-versions-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-packaging-plugin</artifactId>
				<configuration>
					<strictVersions>false</strictVersions>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-compiler-plugin</artifactId>
				<configuration>
					<compilerArgument>-err:-forbidden,discouraged,deprecation</compilerArgument>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-source-plugin</artifactId>
				<version>${tycho-version}</version>
				<executions>
					<execution>
						<id>plugin-source</id>
						<goals>
							<goal>plugin-source</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho-version}</version>
				<configuration>

					<pomDependencies>consider</pomDependencies>
					<executionEnvironment>JavaSE-1.8</executionEnvironment>
					<dependency-resolution>
						<extraRequirements>
							<requirement>
								<type>eclipse-plugin</type>
								<id>com.ibm.notes.java.api.win32.linux</id>
								<versionRange>9.0.1</versionRange>
							</requirement>
							<requirement>
								<type>eclipse-plugin</type>
								<id>org.openntf.domino.java.api.corba.patch</id>
								<versionRange>0.0.0</versionRange>
							</requirement>
						</extraRequirements>
					</dependency-resolution>
				</configuration>
			</plugin>
			<plugin>
				<!-- javadoc configuration -->
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>

					<failOnError>false</failOnError>
					<excludePackageNames>com.sun.*:com.ibm.commons.*:com.ibm.sbt.core.*:com.ibm.sbt.plugin.*:com.ibm.sbt.jslibrray.*:com.ibm.sbt.proxy.*:com.ibm.sbt.security.*:*.util.*:com.ibm.sbt.portlet.*:com.ibm.sbt.playground.*:demo.*:acme.*</excludePackageNames>

					<charset>UTF-8</charset>
					<encoding>UTF-8</encoding>
					<docencoding>UTF-8</docencoding>
					<breakiterator>true</breakiterator>
					<version>true</version>
					<author>true</author>
					<keywords>true</keywords>
				</configuration>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>

		<pluginManagement>
			<plugins>
				<plugin>
					<artifactId>maven-jar-plugin</artifactId>
					<version>2.6</version>
					<configuration>
						<archive>
							<manifestFile>${manifest-location}/MANIFEST.MF</manifestFile>
						</archive>
					</configuration>
				</plugin>
				<!-- This is to enable test execution only on supported platforms below -->
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-surefire-plugin</artifactId>
					<version>${tycho-version}</version>
					
					<configuration>
						<skip>true</skip>
						<encoding>UTF-8</encoding>
						<inputEncoding>UTF-8</inputEncoding>
						<outputEncoding>UTF-8</outputEncoding>
						<argLine>${tycho.testArgLine} -Dfile.encoding=UTF-8</argLine>
						<providerHint>junit4</providerHint>
						<failIfNoTests>false</failIfNoTests>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-maven-plugin</artifactId>
					<version>${tycho-version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-versions-plugin</artifactId>
					<version>${tycho-version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-packaging-plugin</artifactId>
					<version>${tycho-version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-p2-repository-plugin</artifactId>
					<version>${tycho-version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-compiler-plugin</artifactId>
					<version>${tycho-version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<profiles>
		<!-- These profiles add support for specific platforms for tests -->
		<profile>
			<activation>
				<os>
					<family>Windows</family>
				</os>
				<property>
					<name>notes-program</name>
				</property>
			</activation>
		
			<build>
				<plugins>
					<plugin>
						<groupId>org.eclipse.tycho</groupId>
						<artifactId>tycho-surefire-plugin</artifactId>
						<version>${tycho-version}</version>
						
						<configuration>
							<skip>false</skip>
							
							<argLine>-Dfile.encoding=UTF-8 -Djava.library.path="${notes-program}"</argLine>
							<environmentVariables>
								<PATH>${notes-program}${path.separator}${env.PATH}</PATH>
							</environmentVariables>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>mac</id>
			<activation>
				<os>
					<family>mac</family>
				</os>
				<property>
					<name>notes-program</name>
				</property>
			</activation>
		
			<build>
				<plugins>
					<plugin>
						<groupId>org.eclipse.tycho</groupId>
						<artifactId>tycho-surefire-plugin</artifactId>
						
						<configuration>
							<skip>false</skip>
							
							<argLine>-Dfile.encoding=UTF-8 -Djava.library.path="${notes-program}"</argLine>
							<environmentVariables>
								<PATH>${notes-program}${path.separator}${env.PATH}</PATH>
								<LD_LIBRARY_PATH>${notes-program}${path.separator}${env.LD_LIBRARY_PATH}</LD_LIBRARY_PATH>
								<DYLD_LIBRARY_PATH>${notes-program}${path.separator}${env.DYLD_LIBRARY_PATH}</DYLD_LIBRARY_PATH>
								<Notes_ExecDirectory>${notes-program}</Notes_ExecDirectory>
							</environmentVariables>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>linux</id>
			<activation>
				<os>
					<family>unix</family>
					<name>linux</name>
				</os>
				<property>
					<name>notes-program</name>
				</property>
			</activation>
		
			<build>
				<plugins>
					<plugin>
						<groupId>org.eclipse.tycho</groupId>
						<artifactId>tycho-surefire-plugin</artifactId>
						<version>${tycho-version}</version>
						
						<configuration>
							<skip>false</skip>
							
							<argLine>-Dfile.encoding=UTF-8 -Djava.library.path="${notes-program}"</argLine>
							<environmentVariables>
								<!-- The res/C path entry is important for loading formula language properly -->
								<PATH>${notes-program}${path.separator}${notes-program}/res/C${path.separator}${notes-data}${path.separator}${env.PATH}</PATH>
								<LD_LIBRARY_PATH>${notes-program}${path.separator}${env.LD_LIBRARY_PATH}</LD_LIBRARY_PATH>
								
								<!-- Notes-standard environment variable to specify the program directory -->
								<Notes_ExecDirectory>${notes-program}</Notes_ExecDirectory>
								<Directory>${notes-data}</Directory>
								
								<!-- Linux generally requires that the notes.ini path be specified manually, since it's difficult to determine automatically -->
								<!-- This variable is a convention used in the NAPI test classes, not Notes-standard -->
								<NotesINI>${notes-ini}</NotesINI>
							</environmentVariables>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>